# site-ops-runner/.github/workflows/runner-build.yml
name: Build & Publish runner

on:
  push:
    paths:
      - 'Dockerfile.runner'
      - 'smoke-tests/**'
      - 'VERSION'
      - '.github/workflows/runner-build.yml'
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'   # weekly rebuild (security updates)

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/site-ops-runner

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # for keyless cosign (optional)
    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: v
        run: |
          VER="$(cat VERSION)"
          echo "ver=$VER" >> "$GITHUB_OUTPUT"
          echo "minor=${VER%.*}" >> "$GITHUB_OUTPUT"
          echo "major=${VER%%.*}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (multi-arch)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.runner
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:v${{ steps.v.outputs.ver }}
            ${{ env.IMAGE_NAME }}:${{ steps.v.outputs.major }}
            ${{ env.IMAGE_NAME }}:${{ steps.v.outputs.minor }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.version=v${{ steps.v.outputs.ver }}
            org.opencontainers.image.revision=${{ github.sha }}
          provenance: false  # set true if you want buildkit attestations
          sbom: false        # we’ll generate SBOM separately
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Extract image digest
        id: digest
        run: |
          echo "digest=${{ steps.build.outputs.digest }}" >> "$GITHUB_OUTPUT"

      # Optional: SBOM & vuln scan
      - name: Generate SBOM (syft)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_NAME }}@${{ steps.digest.outputs.digest }}
          artifact-name: sbom-runner.spdx.json

      - name: Scan (trivy)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}@${{ steps.digest.outputs.digest }}
          format: table
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # Optional: sign the image via keyless cosign
      - name: Cosign sign
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          curl -sSL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o cosign
          chmod +x cosign
          ./cosign sign --yes ${{ env.IMAGE_NAME }}@${{ steps.digest.outputs.digest }}

  smoke:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull runner image by digest
        run: docker pull ${{ env.IMAGE_NAME }}@${{ needs.build.outputs.digest }}

      - name: Run smoke tests inside runner
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            ${{ env.IMAGE_NAME }}@${{ needs.build.outputs.digest }} \
            /work/smoke-tests/verify-tools.sh || exit 1
